Added toolbar and headline (Mobile View)
Luiscarlosvd/personal-portfolio pull request #1
Opened 2023-03-22 21:29 UTC by Luiscarlosvd

- Added a header section with a button for the menu
- Added a headline section in the main with the principal text of the project and social media icons

2023-03-22 21:46 UTC, binhussen requested changes
Hi @Luiscarlosvd , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 21:46 UTC, binhussen commented on index.html
> +            </div>
- Kindly, Use a `ul` tag to group the list of icons, and `li` per icon; each icon has a link (`a` tag), this conversion used Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using `href` :+1: .

2023-03-22 21:46 UTC, binhussen commented on index.html
> +        </button>
- Kindly wrap your hamburger button with a `nav` tag for semantics reasons :+1: .

2023-03-22 21:46 UTC, binhussen commented on style.css
> +.header {
- Kindly, by default, some HTML tags have some margin and padding, which leads your background image to have mrgin:8, so please reset it with bellow  :-1:  code 
```
* {
margin: 0;
padding: 0;
}
```

2023-03-23 00:33 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @Luiscarlosvd , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 00:35 UTC, merged